#!/bin/bash
result=$(echo "ibase=water;obase=bestchol;$(echo "$WATER" | tr 'abcdefghijklmnopqrstuvwxyz' '0123456789')" + "ibase=stir;obase=bestchol;$(echo "$STIR" | tr 'abcdefghijklmnopqrstuvwxyz' '0123456789')" | bc)
echo "$result" | tr '0123456789' 'abcdefghij'
